spring.application.name=Projeto-Inclure
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.grfvwwevhqevhlengnwu
spring.datasource.password=m7sArioDeC0dific4

api.security.token.secret=${JWT_SECRET:my-secret-key}
